language: python
jobs:
  include:
    - stage:
      python: 3.6
      env: TOXENV=flake8
    - stage:
      python: 2.7
      env: TOXENV=py27
    - stage:
      python: 3.4
      env: TOXENV=py34
    - stage:
      python: 3.5
      env: TOXENV=py35
    - stage:
      python: 3.6
      env: TOXENV=py36
    - stage:
      python: pypy
      env: TOXENV=pypy
    - stage:
      python: pypy3
      env: TOXENV=pypy3

cache:
  pip: true
install: pip install tox
script: tox